# Generated by Django 5.2.6 on 2025-09-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_message_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
